export const ACTION = {
    LOAD_BOOKS: 'LOAD_BOOKS',
    ADD_TO_CART: 'ADD_TO_CART',
    CLEAR_CART: 'CLEAR_CART',
    ADD_TO_ORDERS: 'ADD_TO_ORDERS',
    BOOKS_LOADED: 'BOOKS_LOADED',
    LOADING_BOOKS: 'BOOKS_LOADING',
    LOAD_BOOKS_FAILED: 'LOAD_BOOKS_FAILED'
}